version: '3'
services:
#   server: # We can add other specific layouts (server as example)
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     ports:
#       - "9000:9000"
#     container_name: server
#     volumes:
#        - ./:/usr/src/app
#        - /usr/src/app/node_modules
#     command: npm run server
  frontend-aio:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      - "49153:49153"
      - "8080:8080"
      - "9099:9099"
      - "5000:5000"
      - "4000:4000"
    container_name: frontend-aio
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules
    command: [sh, -c, "npm run firebase:emulator:start & npm run start"]
  frontend-test-aio:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9876:9876"
    container_name: frontend-test-aio
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules
    command: npm run test
